import Head from "next/head";
import MainHome from "@/components/pageComponents/home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Harold's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainHome />
      </main>
    </>
  );
}
